name: Code Review
on: [push]
  
jobs:
  CodeReview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      ################################
      # Super Linter #
      ################################
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          VALIDATE_PYTHON: true
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_PYTHON_FLAKE8: true
          VALIDATE_PYTHON_ISORT: true
          VALIDATE_PYTHON_MYPY: true
          VALIDATE_PYTHON_PYLINT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ################################
      # CodeQL #
      ################################
      # - name: Initialize CodeQL
      #   if: always()
      #   uses: github/codeql-action/init@v1
      #   with:
      #     languages: go, javascript

      # # Here is where you build your code
      # - run: |
      #     make bootstrap
      #     make release

      # - name: Perform CodeQL Analysis
      #   if: always()
      #   uses: github/codeql-action/analyze@v1