name: Code Review
on: [push]
  
jobs:
  CodeReview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      ################################
      # Super Linter #
      ################################
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_PYTHON: true
          DEFAULT_BRANCH: main
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_PYTHON_FLAKE8: true
          VALIDATE_PYTHON_ISORT: true
          VALIDATE_PYTHON_MYPY: true
          VALIDATE_PYTHON_PYLINT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      ################################
      # PyRight                     #
      ################################
      - name: Install PyRight Plugins
        if: always()
        run: pip3 install pyright

      - name: Run PyRight
        if: always()
        run: pyright .
      
      ################################
      # PyRe                       #
      ################################
      - name: Install PyRe Plugins
        if: always()
        run: pip3 install pyre-check

      - name: Run PyRe
        if: always()
        run: |
          echo . | pyre init
          pyre
      ################################
      # pycodestyle                  #
      ################################
      - name: Install pycodestyle Plugins
        if: always()
        run: pip3 install pycodestyle

      - name: Run pycodestyle
        if: always()
        run: pycodestyle .

      ################################
      # bandit                  #
      ################################
      - name: Install bandit Plugins
        if: always()
        run: pip3 install bandit

      - name: Run bandit
        if: always()
        run: bandit -r .
      
      ################################
      # vulture                  #
      ################################
      - name: Install vulture Plugins
        if: always()
        run: pip3 install vulture

      - name: Run vulture
        if: always()
        run: vulture .
       ################################
      # semgrep                  #
      ################################
      - name: Install semgrep Plugins
        if: always()
        run: python3 -m pip install semgrep

      - name: Run vulture
        if: always()
        run: |
          semgrep --config "p/ci" .
          semgrep --config "p/r2c-ci" .
          semgrep --config "p/python" .
 

